train: [0]
test: [1]
plot: [0]
load: [1]

model: [Cui2020Learnable_34_10_LBGAT6, Cui2020Learnable_34_10_LBGAT0, Sitawarin2020Improving, Chen2020Efficient, Wu2020Adversarial, Rice2020Overfitting, Hendrycks2019Using]
model_norm: "Linf"
dataset: [cifar100]
pretrained: [True]
lr_schedule: [step_wise]
optimizer: [sgdm]
attacks: [[
          {"type":apgd, "key":"apgd_accuracy", "iters":100, "restarts":1, "norm": linf, "loss":"cw"},
          {"type":apgd, "key":"apgd_accuracy", "iters":100, "restarts":1, "norm": linf, "batch_tune":{"sigma":[0.05, 0.1, 0.15, 0.2, 0.25]}, "loss":"jitter"},
          {"type":apgd, "key":"apgd_accuracy", "iters":100, "restarts":1, "norm": linf, "loss":"ce"},
          {"type":apgd, "key":"apgd_accuracy", "iters":100, "restarts":1, "norm": linf, "loss":"dlr"}
          ]]
que_attacks: False
test_size: 1
result_path: Results
seed: [0]
batch_size: [50]